### ISSUE TITLE
Upload package fails to validate credentials 

### ISSUE THREAD

**Issue by doronAtuar** [sonatype-nexus-community/nexus-repository-conan#39] opened 2018-12-24 12:22 UTC
I'm trying to upload a package.
```bash
conan user -r my-conan -p password username
conan upload utils/1.5.0@demo/demo -r my-conan
```

For some reason it keeps asking for the password even after I re-entered the right one.
```bash
Are you sure you want to upload 'utils/1.5.0@demo/demo'? (yes/no): yes
Uploading utils/1.5.0@demo/demo to remote 'my-conan'
Please log in to "my-conan" to perform this action. Execute "conan user" command.
Please enter a password for "upload" account: You pressed Ctrl+C!
```
This seems to reproduce with Ubuntu 16

See also the description of @dhoer:
https://github.com/conan-io/conan/issues/4190

My Nexus server was configured as follows:

- I've up Conan repository correctly as you described in README.md.
- I've configured a hosted Conan repository
- I gave _username_ `nx-repository-view-*-*-*` `nx-repository-admin-conan-syte_conan-*` permissions
- _passord_ is the nexus _username_ password

Conan version 1.11.0

**Comment by doddi** [comment] 2018-12-25 05:42
Have you added the Conan Bearer in the set up?

See point 3 of https://github.com/sonatype-nexus-community/nexus-repository-conan/blob/master/docs/CONAN_USER_DOCUMENTATION.md

**Comment by dhoer** [comment] 2018-12-26 19:09
@DarthHater It looks like the problem with `conan user` command failing on Ubuntu 16.04 is a nexus-repository-plugin issue according to https://github.com/conan-io/conan/issues/4190#issuecomment-449719771.  Not sure how to go about troubleshooting this issue. Any ideas?

**Comment by DarthHater** [comment] 2018-12-27 02:38
I've spent some time looking at this today, and the short is I cannot recreate it, but I'm also not going fully down the rabbit hole (yet). The big differences in my setup locally when I tested it was I did not setup SSL for Nexus Repo, and I'm testing over http. Using http thus far, I am able to login with conan. I've sent some extra info to @dhoer , I added some code to my local version of conan that set debug for the python urllib3 stuff, so that I can see responses. It would be neat to do this on the ubuntu machine you are running, and see what it's getting when trying to communicate with Nexus Repo. I'll circle back with you when you are back from the holidays!

**Comment by dhoer** [comment] 2018-12-27 16:40
@DarthHater Thanks for spending time on this.  That is interesting that http is working.  I use AWS ALB and terminate a wildcard ssl cert there. I can publish a modified version of our terraform on github that creates the environment, if you would like.  The x-forwarded headers comes to mind:https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html.  But I really doubt that is the issue since MacOS works.

**Comment by doddi** [comment] 2019-01-10 14:35
@dhoer @doronAtuar I have done a little digging today but unfortunately I have not been able to reproduce the problem (I also have been using a mac). This at least puts the issue down to ubuntu (hopefully).
I used the same set up as you describe including using SSL.

`conan upload testlib/1.0@demo/testing -r conan-hosted
/usr/local/Cellar/conan/1.11.2/libexec/lib/python3.7/site-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for localhost has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
Uploading testlib/1.0@demo/testing to remote 'conan-hosted'
Uploading conanmanifest.txt
[==================================================] 58B/58B
Uploading conanfile.py
[==================================================] 1.7KB/1.7KB
Uploaded conan recipe 'testlib/1.0@demo/testing' to 'conan-hosted': https://localhost:8443/repository/conan-hosted`

I will proceed to try and set up an Ubuntu box to see if I can replicate this in any way. At least we have narrowed down the issue further.

In the meantime is it possible to supply a support.zip after an upload failure occurs. It could help track it down. See https://support.sonatype.com/hc/en-us/articles/223243768-Support-Ticket-Best-Practices on how to generate a support.zip.

Out of curiosity is the username and password used on the jenkins box standard ASCII, i.e. nothing cryptic that could be causing the issue?

**Comment by dhoer** [comment] 2019-01-10 22:48
@doddi I'm using a 32 char password that contains number and upper/lower characters. I was able to duplicate it using an Ubuntu 16.04 docker image running on my macOS.  I think I was also able to see the same issue on centos as well.  I would have to ping @DarthHater to verify that though.  

Does sonatype scrub data before it zips it?

**Comment by doddi** [comment] 2019-01-11 07:55
@dhoer it does scrub data on the support.zip. 
If you are able to reproduce it using a docker image then that will suffice. That was going to be my next step.  Can you provide your DockerFile to save me having to write one? I have been using a docker container for most of my earlier testing but it probably wasn't ubuntu (`FROM python:2.7`)

**Comment by dhoer** [comment] 2019-01-22 23:17
@doddi @DarthHater The problem was environment related on my side.  This is now fixed for me.  Thank you for your help.

**Comment by DarthHater** [comment] 2019-01-22 23:22
@dhoer you are very welcome! Do you know what the issue was in case anyone else runs into it?

**Comment by doddi** [comment] 2019-01-23 09:33
@dhoer awesome news, thanks for getting back to us

**Closed** 2019-01-24 12:44 UTC
