### ISSUE TITLE
Trying to download a package always return true

### ISSUE THREAD

**Issue by rea-yseop** [sonatype-nexus-community/nexus-repository-conan#119] opened 2020-04-30 15:00 UTC
* **What are you trying to do?**

I have a nexus with the plugin containing some packages.
I also have packages from others remotes.
So i have something like
```
conan remote add my_nexus <url> --force --insert=0
conan remote add conan-center https://conan.bintray.com --force --insert=1
```

I then try to install a lib from conan-center (for example zlib) which does not exist in my_nexus. However for some reason, it "finds" zlib and dowloads it resulting with an empty package.

On the left, the correct behavior on a previous version. On the right, the current behavior with version 3.22
![image](https://user-images.githubusercontent.com/46320869/80724989-cb95a980-8b02-11ea-85e2-2aa9074c0cb9.png)

For now i fixed that by changing the order of priority.

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
N/A

* **Anything else?**
N/A

**Comment by igorudovika** [comment] 2020-04-30 18:15
Hello @rea-yseop 
What version of conan client are you using? It looks like you have some problems with local cache. Could you run `conan remove zlib/1.2.11@conan/stable` and repeat `conan install zlib/1.2.11@conan/stable` command. If it will not help could you switch conan client into debug level, just execute command: `export CONAN_LOGGING_LEVEL=10` and provide conan install command output?
Also one more question, it looks like left output is from conan-central installation, not from previous version of NRXM conan plug-in. Could you check and confirm?
Thanks, Igor.

**Comment by rea-yseop** [comment] 2020-05-04 07:34
Hello,

I tried with conan version 1.19.1 and 1.24.
I don't think it's a cache problem because i ran the command `conan remove "*" -f` before. And it's also "Not found in local cache". 
As you said, on the left output, zlib is taken from conan-central because it is not in our nexus which is what i want. It's `Trying with nexus` then `Trying with conan-center`
On the right output, `Trying with nexus` is successful when it should not.

Same as before but with conan logging level at 10
![image](https://user-images.githubusercontent.com/46320869/80944596-39372380-8dea-11ea-89bc-4951e044fc61.png)

**Comment by igorudovika** [comment] 2020-05-04 11:14
Hello,
thanks for update. To start investigation I need to ensure. As I understood your nexus repo is hosted one, not proxy. Could you confirm?

**Comment by rea-yseop** [comment] 2020-05-04 11:18
Yes, this is a hosted repo.

**Comment by igorudovika** [comment] 2020-05-04 11:26
Are you working with NRXM 3.22.0? We have fixed problem in 3.22.1 with Conan hosted repo that can be a cause of issue you have encountered. Could you try with 3.22.1 version?

**Comment by rea-yseop** [comment] 2020-05-04 11:29
We are already on 3.22.1-02.

**Comment by igorudovika** [comment] 2020-05-04 11:33
ok, thanks. I need some time to investigate issue.

**Comment by topheg** [comment] 2020-06-15 18:59
Hello,
Is there any news on this ?
I have the exact same problem, with conan install working when the package can be found on my nosted nexus repo, but conan not trying to fallback to conan-central when it is not (the remotes are correctly configured)
I could share the output logs, but they are similar to the ones from rea-yseop.

I tested with NRXM 3.23.0-03, conan 1.11.0 and 1.22.0.

**Comment by igorudovika** [comment] 2020-06-22 13:55
Hello, sorry for late response. Conan Hosted is still not officially supported so fixing of such issues can take a time. We have reproduced this one and investigated the root cause. Once https://github.com/sonatype-nexus-community/nexus-repository-conan/pull/127 or similar fix will be merged this issue should be resolved.

**Comment by igorudovika** [comment] 2020-09-03 07:30
Should be fixed since NXRM 3.26

**Closed by igorudovika** 2020-09-03 07:30 UTC
