### ISSUE TITLE
Cannot upload openssl package to Nexus3 hosted conan repository

### ISSUE THREAD

**Issue by jheaff1** [sonatype-nexus-community/nexus-repository-conan#113] opened 2020-04-03 13:39 UTC
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Upload the openssl/1.0.2t package from conan-center to my Nexus3 hosted conan repository

* **What feature or behavior is this required for?**
Hosting a conan repository in Nexus3

* **How could we solve this issue? (Not knowing is okay!)**
Don't know, I'm afraid

* **Anything else?**
I am running a CentOS 7 machine with GCC 4.8 installed. I am building the MD5 example application: https://github.com/conan-io/examples/tree/master/libraries/poco/md5

The dependencies of the MD5 application are openssl/1.0.2t, poco/1.9.4 and zlib/1.2.11. "conan install" failed as none of the dependencies in conan-center are built for GCC 4.8. Therefore i ran "conan install --build missing" and successfully built the dependencies and the MD5 application using GCC 4.8.

I then wished to upload openssl, poco and zlib built with GCC 4.8 to my local Nexus3 hosted conan repository.

After running "conan upload "*" --all -r=my-conan-repo", the following text is printed to the console:

```
Are you sure you want to upload 'openssl/1.0.2t' to 'my-conan-repo'? (yes/no): yes
Are you sure you want to upload 'poco/1.9.4' to 'my-conan-repo'? (yes/no): yes
Are you sure you want to upload 'zlib/1.2.11' to 'my-conan-repo'? (yes/no): yes
Uploading to remote 'my-conan-repo':
Uploading openssl/1.0.2t to remote 'my-conan-repo'                                      
Uploaded conan_export.tgz -> openssl/1.0.2t [0.24k]                                      
ERROR: 
Error uploading file: conan_sources.tgz, ''conan_sources.tgz''
Uploaded conanfile.py -> openssl/1.0.2t [30.67k]                                         
Uploaded conanmanifest.txt -> openssl/1.0.2t [0.10k]                                     
Uploading poco/1.9.4 to remote 'my-conan-repo'                                          
Uploaded conan_export.tgz -> poco/1.9.4 [0.25k]                                          
Uploaded conan_sources.tgz -> poco/1.9.4 [0.30k]                                         
Uploaded conanfile.py -> poco/1.9.4 [8.95k]                                              
Uploaded conanmanifest.txt -> poco/1.9.4 [0.17k]                                         
Uploaded conan recipe 'poco/1.9.4' to 'my-conan-repo': http://localhost:8081/repository/my-conan-repo/
Uploading zlib/1.2.11 to remote 'my-conan-repo'                                         
Uploaded conan_export.tgz -> zlib/1.2.11 [0.23k]                                         
Uploaded conan_sources.tgz -> zlib/1.2.11 [6.91k]                                        
Uploaded conanfile.py -> zlib/1.2.11 [7.59k]                                             
Uploaded conanmanifest.txt -> zlib/1.2.11 [0.29k]                                        
Uploaded conan recipe 'zlib/1.2.11' to 'my-conan-repo': http://localhost:8081/repository/my-conan-repo/
Uploading package 1/1: 70254466a5d0be5114bc812abc39153e346ebdb8 to 'my-conan-repo'      
Package is up to date, upload skipped
Uploading package 1/1: 3a5f72c8cd50641b8efa6ed13e6914c6ced2747c to 'my-conan-repo'      
Package is up to date, upload skipped
ERROR: openssl/1.0.2t: Upload recipe to 'my-conan-repo' failed: Execute upload again to retry upload the failed files: conan_sources.tgz. [Remote: my-conan-repo]

ERROR: Errors uploading some packages

```

poco and zlib uploaded successfully but openssl did not

**I am running Nexus OSS 3.22.0-02, using the built-in Conan plugin (version 1.0.1)**

**Comment by jheaff1** [comment] 2020-04-03 14:01
It is worth noting that I could successfully upload openssl to my Nexus3 conan repository using this version of the plugin (again, with Nexus OSS 3.22.0-02):

https://github.com/1BE6-ankit/nexus-repository-conan/tree/hosted-search

**Comment by Austin299792** [comment] 2020-04-14 11:37
I'm testing Conan repository support, but having some issues with the `conan upload --all <package> -r=<remote>`, even when following the simple hello program in Creating Packages > [Getting Started](https://docs.conan.io/en/latest/creating_packages/getting_started.html) (I also tried with binaries compiled at my company for another project). I get the errors below. I believe this error is similar to @jheaff1's. 

I traced it down to that the .tgz files are not being created by conan, so then only the recipe and manifest are available to export, but not the binaries. The 1BE6-ankit fork above has an old commit on 22 Nov 2018 (204789d) that might have fixed this problem.

Any chance this can be tested for the master and next official nxrm release?

> Uploading to remote 'conan-dev-hosted':
Uploading hello/0.1@demo/testing to remote 'conan-dev-hosted'
ERROR:
Error uploading file: conan_export.tgz, ''conan_export.tgz''
ERROR:
Error uploading file: conan_sources.tgz, ''conan_sources.tgz''
Uploaded conanfile.py -> hello/0.1@demo/testing [1.72k]
Uploaded conanmanifest.txt -> hello/0.1@demo/testing [0.06k]
ERROR: hello/0.1@demo/testing: Upload recipe to 'conan-dev-hosted' failed: Execute upload again to retry upload the failed files: conan_export.tgz, conan_sources.tgz. [Remote: conan-dev-hosted]
ERROR: Errors uploading some packages

**Comment by memsharded** [comment] 2020-04-14 14:39
I have compared in https://github.com/conan-io/conan/issues/6847#issuecomment-613481423 the different traces of the servers, and it seems Nexus is doing something different, maybe those traces there can help.

**Comment by Austin299792** [comment] 2020-04-14 17:11
I did some additional testing recommended by @memsharded and confirmed that this only occurs when I'm trying to upload to the Nexus hosted repo and not when uploading to the conan_server or to any server with the `--skip-upload` option. For the latter, the .tgz files are created. If I then run the upload without `--skip-upload`, the upload fails because the .tgz files are not created (even though they still exist in the .conan package directory).

**Comment by Austin299792** [comment] 2020-04-14 18:18
I've been looking at this more. Here is the trace from the successful upload to local conan_server:

```
{"_action": "COMMAND", "name": "upload", "parameters": {"all_packages": true, "confirm": true, "integrity_check": false, "package": null, "parallel_upload": false, "pattern": "hello/0.1", "policy": null, "query": null, "remote_name": "local-repo", "retry": null, "retry_wait": null}, "time": 1586872527.014567}
{"_action": "REST_API_CALL", "duration": 0.007729053497314453, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "demo"}, "method": "GET", "time": 1586872527.041423, "url": "http://0.0.0.0:9300/v1/ping"}
{"_action": "REST_API_CALL", "duration": 0.002844095230102539, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "demo"}, "method": "GET", "time": 1586872527.0447738, "url": "http://0.0.0.0:9300/v1/conans/hello/0.1/demo/testing/digest"}
{"_action": "REST_API_CALL", "duration": 0.0026857852935791016, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "demo"}, "method": "GET", "time": 1586872527.048588, "url": "http://0.0.0.0:9300/v1/users/check_credentials"}
{"_action": "REST_API_CALL", "duration": 0.0028831958770751953, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "demo"}, "method": "GET", "time": 1586872527.052474, "url": "http://0.0.0.0:9300/v1/conans/hello/0.1/demo/testing"}
{"_action": "REST_API_CALL", "duration": 0.005399942398071289, "headers": {"Accept": "application/json", "Content-type": "application/json", "User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "demo"}, "method": "POST", "time": 1586872527.059007, "url": "http://0.0.0.0:9300/v1/conans/hello/0.1/demo/testing/upload_urls"}
{"_action": "REST_API_CALL", "duration": 0.010719060897827148, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Sha1": "987b1bfc0972b502f702f44c0cdbad641ed17295"}, "method": "PUT", "time": 1586872527.0707562, "url": "http://localhost:9300/v1/files/hello/0.1/demo/testing/0/export/conanfile.py?signature=**********"}
{"_action": "REST_API_CALL", "duration": 0.004086017608642578, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Sha1": "de4dbb826993e1bf55da224d4d1f9d8fc147298d"}, "method": "PUT", "time": 1586872527.075833, "url": "http://localhost:9300/v1/files/hello/0.1/demo/testing/0/export/conanmanifest.txt?signature=**********"}
{"_action": "UPLOADED_RECIPE", "_id": "hello/0.1@demo/testing", "duration": 0.04552793502807617, "files": [{"md5": "d2b18e8ee87b91760c2992fd66cdc69d", "name": "conanfile.py", "path": "/Users/austin/.conan/data/hello/0.1/demo/testing/export/conanfile.py", "sha1": "987b1bfc0972b502f702f44c0cdbad641ed17295"}, {"md5": "f231464c319c593943d368cdce74f966", "name": "conanmanifest.txt", "path": "/Users/austin/.conan/data/hello/0.1/demo/testing/export/conanmanifest.txt", "sha1": "de4dbb826993e1bf55da224d4d1f9d8fc147298d"}], "remote": "local-repo", "time": 1586872527.076561}
{"_action": "ZIP", "dst": "/Users/austin/.conan/data/hello/0.1/demo/testing/package/103f6067a947f366ef91fc1b7da351c588d1827f/conan_package.tgz", "duration": 0.006637096405029297, "src": [{"md5": "8727846905bd09baecf8bdc1edb1f46e", "name": "include/hello.h", "path": "/Users/austin/.conan/data/hello/0.1/demo/testing/package/103f6067a947f366ef91fc1b7da351c588d1827f/include/hello.h", "sha1": "5defefc7a8ebde1a1d39989094a11f3aa0b459de"}, {"md5": "50bea6dc72e3234774aeb7673f15c691", "name": "lib/libhello.a", "path": "/Users/austin/.conan/data/hello/0.1/demo/testing/package/103f6067a947f366ef91fc1b7da351c588d1827f/lib/libhello.a", "sha1": "e83eb9ac7b2a6b7c4b008d1621332e24c24127a6"}], "time": 1586872527.0855901}
{"_action": "REST_API_CALL", "duration": 0.0026559829711914062, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "demo"}, "method": "GET", "time": 1586872527.0893319, "url": "http://0.0.0.0:9300/v1/users/check_credentials"}
{"_action": "REST_API_CALL", "duration": 0.011753082275390625, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "demo"}, "method": "GET", "time": 1586872527.1023202, "url": "http://0.0.0.0:9300/v1/conans/hello/0.1/demo/testing/packages/103f6067a947f366ef91fc1b7da351c588d1827f"}
{"_action": "REST_API_CALL", "duration": 0.010400056838989258, "headers": {"Accept": "application/json", "Content-type": "application/json", "User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "demo"}, "method": "POST", "time": 1586872527.1148338, "url": "http://0.0.0.0:9300/v1/conans/hello/0.1/demo/testing/packages/103f6067a947f366ef91fc1b7da351c588d1827f/upload_urls"}
{"_action": "REST_API_CALL", "duration": 0.004307270050048828, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Sha1": "3470e9629a96c97123cfcaf50bd20804a986aefc"}, "method": "PUT", "time": 1586872527.1202922, "url": "http://localhost:9300/v1/files/hello/0.1/demo/testing/0/package/103f6067a947f366ef91fc1b7da351c588d1827f/0/conan_package.tgz?signature=**********"}
{"_action": "REST_API_CALL", "duration": 0.005776882171630859, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Sha1": "b9e8b358e73d3c338d0c6458b3b4fa81eef0b7e1"}, "method": "PUT", "time": 1586872527.12706, "url": "http://localhost:9300/v1/files/hello/0.1/demo/testing/0/package/103f6067a947f366ef91fc1b7da351c588d1827f/0/conaninfo.txt?signature=**********"}
{"_action": "REST_API_CALL", "duration": 0.0038521289825439453, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Sha1": "ae95ec316f38b1fc19f804b2493880cb4092e4a8"}, "method": "PUT", "time": 1586872527.1327271, "url": "http://localhost:9300/v1/files/hello/0.1/demo/testing/0/package/103f6067a947f366ef91fc1b7da351c588d1827f/0/conanmanifest.txt?signature=**********"}
{"_action": "UPLOADED_PACKAGE", "_id": "hello/0.1@demo/testing:103f6067a947f366ef91fc1b7da351c588d1827f", "duration": 0.05479121208190918, "files": [{"md5": "2d71694fee9120ed737e591456a83046", "name": "conan_package.tgz", "path": "/Users/austin/.conan/data/hello/0.1/demo/testing/package/103f6067a947f366ef91fc1b7da351c588d1827f/conan_package.tgz", "sha1": "3470e9629a96c97123cfcaf50bd20804a986aefc"}, {"md5": "753ad5bc695dc3ad1d57ac4e21f48457", "name": "conaninfo.txt", "path": "/Users/austin/.conan/data/hello/0.1/demo/testing/package/103f6067a947f366ef91fc1b7da351c588d1827f/conaninfo.txt", "sha1": "b9e8b358e73d3c338d0c6458b3b4fa81eef0b7e1"}, {"md5": "1957f6a2b971c62e508ca7496a0df812", "name": "conanmanifest.txt", "path": "/Users/austin/.conan/data/hello/0.1/demo/testing/package/103f6067a947f366ef91fc1b7da351c588d1827f/conanmanifest.txt", "sha1": "ae95ec316f38b1fc19f804b2493880cb4092e4a8"}], "remote": "local-repo", "time": 1586872527.133416}
```

and the trace for the unsuccessful upload to the nexus conan hosted repo:

```
{"_action": "COMMAND", "name": "upload", "parameters": {"all_packages": true, "confirm": true, "integrity_check": false, "package": null, "parallel_upload": false, "pattern": "hello/0.1", "policy": null, "query": null, "remote_name": "conan-dev-hosted", "retry": null, "retry_wait": null}, "time": 1586883780.600357}
{"_action": "REST_API_CALL", "duration": 0.07605695724487305, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "austin"}, "method": "GET", "time": 1586883780.690795, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/v1/ping"}
{"_action": "REST_API_CALL", "duration": 0.017238140106201172, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "austin"}, "method": "GET", "time": 1586883780.7084658, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/v1/conans/hello/0.1/demo/testing/digest"}
{"_action": "REST_API_CALL", "duration": 0.02100992202758789, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0"}, "method": "GET", "time": 1586883780.730093, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/conans/demo/hello/0.1/testing/conanmanifest.txt"}
{"_action": "REST_API_CALL", "duration": 0.07596588134765625, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "austin"}, "method": "GET", "time": 1586883780.8087392, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/v1/users/check_credentials"}
{"_action": "REST_API_CALL", "duration": 0.019405126571655273, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "austin"}, "method": "GET", "time": 1586883780.8291981, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/v1/conans/hello/0.1/demo/testing"}
{"_action": "REST_API_CALL", "duration": 0.01497793197631836, "headers": {"Accept": "application/json", "Content-type": "application/json", "User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "austin"}, "method": "POST", "time": 1586883780.845387, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/v1/conans/hello/0.1/demo/testing/upload_urls"}
{"_action": "REST_API_CALL", "duration": 0.02141594886779785, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Deploy": "true", "X-Checksum-Sha1": "987b1bfc0972b502f702f44c0cdbad641ed17295"}, "method": "PUT", "time": 1586883780.8675451, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/conans/demo/hello/0.1/testing/conanfile.py"}
{"_action": "REST_API_CALL", "duration": 0.02704906463623047, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Sha1": "987b1bfc0972b502f702f44c0cdbad641ed17295"}, "method": "PUT", "time": 1586883780.89535, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/conans/demo/hello/0.1/testing/conanfile.py"}
{"_action": "REST_API_CALL", "duration": 0.026585102081298828, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Deploy": "true", "X-Checksum-Sha1": "0fb8a5d9d4e7ea619a8939dcacd864ffb5c31b7c"}, "method": "PUT", "time": 1586883780.922549, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/conans/demo/hello/0.1/testing/conanmanifest.txt"}
{"_action": "REST_API_CALL", "duration": 0.07306790351867676, "headers": {"User-Agent": "Conan/1.23.0 (Python 3.7.3) python-requests/2.23.0", "X-Checksum-Sha1": "0fb8a5d9d4e7ea619a8939dcacd864ffb5c31b7c"}, "method": "PUT", "time": 1586883780.996346, "url": "https://nexusrm.qrypt.net:8443/repository/conan-dev-hosted/conans/demo/hello/0.1/testing/conanmanifest.txt"}
{"_action": "EXCEPTION", "class": "ConanException", "message": "Errors uploading some packages", "time": 1586883781.014657}
```

The upload is failing at the step before creating the tgz files, which is the step where `conan upload` PUTs the `conanmanifest.txt`. Maybe nxrm is doing something conan is not expecting and throwing an exception.

**Comment by mrmateo** [comment] 2020-04-14 23:01
It looks like the server is expecting (requiring) there to be a conan_export.tgz file and errors out if one is not uploaded. If you create one (even if it is empty, 0 bytes) the upload appears to work.

I believe this is a _regression_ as upload works fine with 0.0.6. We were able to deploy 0.0.6 to our server running Nexus 3.22.0 but it appears some APIs changed internally and are preventing users from browsing a Conan v0.0.6-based repository on the UI: ```
org.sonatype.nexus.extdirect.internal.ExtDirectExceptionHandler - Failed to invoke action method: coreui_Browse.read, java-method: org.sonatype.nexus.coreui.BrowseComponent.read
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at org.sonatype.repository.conan.internal.ui.ConanBrowseNodeFilter.test(ConanBrowseNodeFilter.java:1)
	at org.sonatype.nexus.repository.browse.internal.orient.OrientBrowseNodeStoreImpl.lambda$14(OrientBrowseNodeStoreImpl.java:255)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)```

**Comment by Austin299792** [comment] 2020-04-15 12:56
Hello @mrmateo, do you have a recommendation for a path forward? I can continue working with the conan team to try to understand why the tgz files are not being created. We're having a hard time understanding why `conan upload` exits before creating the tgz files, based on what it's getting back from the Nexus server.

**Comment by Austin299792** [comment] 2020-04-15 19:40
I found the issue and have detailed it in https://github.com/conan-io/conan/issues/6847#issuecomment-614240287.

**Comment by Austin299792** [comment] 2020-04-16 16:14
Okay, I've done much more digging. Please see the thread here https://github.com/conan-io/conan/issues/6847#issuecomment-614716764. It turns out that the `conan_upload` sends a PUT request to the Nexus server with args with a dictionary that has only the `conanfile.py` and `conanmanifest.py` filenames and file sizes in `data`. But the Nexus repository is returning a dictionary that includes `conan_export.tgz` and `conan_sources.tgz` filename and URLs in addition to conanfile.py` and `conanmanifest.py` filenames and URLs. The problem is that the conan recipe upload fails because those .tgz files don't exist--they're created after the conanfile.py` and `conanmanifest.py` files are uploaded to the repository. 

I have confirmed that this unintended return from the PUT request does not happen when uploading to the local/remote conan_server. Only conanfile.py` and `conanmanifest.py` filenames and URLs are returned, those files are uploaded, then the conan `uploader.py` module can move on to creating and uploading the .tgz files.

I suppose I could start digging through Nexus source code and see if I can find why the .tgz filenames and URLs are being returned from that PUT from `conan upload`, but I would appreciate any assistance from the Nexus community.

**Comment by memsharded** [comment] 2020-04-16 17:08
Great job tracking the issue. I think it is a hardcoded list here: https://github.com/sonatype-nexus-community/nexus-repository-conan/blob/c7df8084793d56bd2b78ce29ba53fc69786099cf/nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedMetadataFacetSupport.java#L48. It shouldn't be hardcoded, it should take the inputs and process them.

**Comment by igorudovika** [comment] 2020-04-17 13:14
@Austin299792 thank for providing this info. Issue that you encountered with should be fixed since NXRM 3.22.1

**Comment by igorudovika** [comment] 2020-04-17 13:25
@jheaff1 provided by you error log looks like a little bit different from error on @Austin299792 message. So potentially it also was fixed in NXRM 3.22.1. But I am not sure. So if yours upload failed because missing of conan_export.tgz then it should be fixed. But looks like it was problem with conan_sources.tgz upload. Seems this one is mandatory for uploading. I have faced with such error when I hadn't such one on my workstation. Configuring proxy repo solved it. I mean Conan client, when it can't find conan_sources.tgz for upload then it try to download it from available proxy.

**Comment by memsharded** [comment] 2020-04-17 13:39
>  But looks like it was problem with conan_sources.tgz upload. Seems this one is mandatory for uploading. 

No, conan_sources.tgz is not mandatory. Only packages with ``exports_sources`` field will have this file. Many packages will not have this artifact at all.

**Comment by igorudovika** [comment] 2020-04-17 15:58
@memsharded I got it. Thanks for your help.

**Comment by igorudovika** [comment] 2020-04-17 16:00
@jheaff1  I was able to reproduce your issue with NXRM 3.22.0 and it works properly on my side on with 3.22.1. Can you try new version?
Thanks Igor.

**Comment by Austin299792** [comment] 2020-04-17 16:09
I upgraded to 3.22.1 and my problem has been resolved! Thank you!

**Comment by jheaff1** [comment] 2020-04-19 11:30
@igorudovika  I too can confirm that after upgrading the 3.22.1 the problem has been resolved!

May I ask when hosted Conan repositories will be officially supported by Nexus?

**Comment by jlstephens89** [comment] 2020-04-20 12:13
@jheaff1 We don't have an official date yet as we have some higher priority and blocking items to get through. We are tracking demand and will circle back when we can.

**Comment by igorudovika** [comment] 2020-04-21 05:04
Issue is resolved, question is answered. Closing.

**Closed by igorudovika** 2020-04-21 05:04 UTC
